name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install python-common
        run: |
          pip install -e libs/python-common
      - name: Lint placeholder
        run: echo "Lint step placeholder"
      - name: Test python-common
        run: |
          pip install pytest
          pytest -q libs/python-common/tests

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        working-directory: frontend
        run: npm ci || npm install
      - name: Build
        working-directory: frontend
        run: npm run build

